config/routes.rb
Rails.application.routes.draw do
  get '/admin', to:'home#admin'
  root to: 'home#index'
  get 'orders/show/:order_id', to:'order#show', as: 'orders_show'
  get 'orders/new', to:'order#new'

  #Carts routes
  get 'carts/show', to:'carts#show'
 
  post 'carts/create', to:'carts#create'
  post 'carts/add_item/:item_id', to:'carts#add_item', as: 'carts_add_item'
  post 'carts/remove_item', to:'carts#remove_item'
  post 'carts/reset', to:'carts#reset'
  #User_Profile routes
  get '/profile', to: 'home#profile'
  #User_Orders routes
  get '/order/:order_id', to: 'home#user_order', as: 'order'
  #Stripe routes
  get'/store', to:'store#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :charges
  resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true
    validates :image, presence: true
    has_and_belongs_to_many :carts
    # un produit appartient et possede plusieurs commandes
    has_and_belongs_to_many :orders

end

app/models/order.rb
class Order < ApplicationRecord
    #cette commande appartient à cet utilisateur précisément, qu'un seul client par commande.
    #et une commande ne peux servir qu'une seule fois.
    belongs_to :user
    has_and_belongs_to_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :cart

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable      
  #un user peux passer plusieurs commandes.
  has_many :orders

  #create a cart associate to the new user
  after_create do
    Cart.create(user_id: self.id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  #show all items of the cart
  def show
    #select the cart of the log-in user
    if user_signed_in?
      @cart = current_user.cart
      @cart_items = @cart.items

      @cart_value = 0
      @cart_items.each do |item|
        @cart_value += item.price
      end
    else
      redirect_to root_path
    end
  end

  def create
  end

  #add item to the cart
  def add_item  
    #params[item_id]
    if user_signed_in?
      cart = current_user.cart
      item = Item.find(params["item_id"])
      @item_id = item.id
      if cart.items << item
        @items_number = cart.items.count
        puts "#"*20
        puts @item_id 
        respond_to do |format|
          format.html { redirect_to root_path }
          format.js
          #Display an SUCCESS mesage      
          #flash[:notice] = "Item succesfuly added"
        end
      else
        #Display an ERR message
      end
    else
      redirect_to root_path
    end
  end

  #remove item from the cart
  def remove_item
    item = Item.find(params["format"])
    #select the cart of the log-in user
    if user_signed_in?
      cart = current_user.cart
      #check if the item is in the cart
      if item.carts.find(cart.id)
        item.carts.delete(cart)
      end
      redirect_to carts_show_path
    else
      redirect_to root_path
    end
  end

  #re-initialize cart
  def reset
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create

		if user_signed_in?
      @cart = current_user.cart
			@cart_items = @cart.items

			#Creation of the order
			@order = Order.create(user_id: current_user.id)
			@cart_items.each do |item| 
				@order.items << item
			end
			
			#order value
			@order_value = 0
			@order.items.each do |item|
				@order_value += item.price
      end

			#re-initialize cart
			@cart_items.each do |item|
				if item.carts.find(@cart.id)
					item.carts.delete(@cart)
				end
			end

			#Send Email to User
			ContactMailer.order(@order, current_user.email).deliver_now
			#Send Email to Admin (ddaviger9@yahoo.fr)
			ContactMailer.order(@order, 'ddaviger9@yahoo.fr').deliver_now

	    else
	      redirect_to root_path
	    end

  		# Amount in cents
	  	@amount = @order_value * 100

	 	 customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  	)

	  	charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount.to_i,
	    :description => 'Downloading files',
	    :currency    => 'eur'
	  	)

		rescue Stripe::CardError => e
	 	flash[:error] = e.message
	  	redirect_to :root

	  	if Order.find_by(current_user.id)
	  		Cart.destroy
	  	end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @items = Item.all
    @admin = User.find_by(admin: true)
    
    @cart_items_id = []
    if user_signed_in?
      current_user.cart.items.each do |item|
        @cart_items_id << item.id
      end
    end

  end

  def show
  	@item_id = Item.find(params[:id])
  end


  def admin
  	@all_users = User.all
  end

  def profile
  	@orders = current_user.orders
  end

  def user_order
    @order = Order.find(params[:order_id])
  end


end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def show
    if user_signed_in?
      @order = Order.find(params['order_id'])
      #order value
      @order_value = 0
			@order.items.each do |item|
				@order_value += item.price
      end
    else
      redirect_to root_path
    end
  end

  def new
    if user_signed_in?
      @cart = current_user.cart
      @cart_items = @cart.items

      @cart_value = 0
      @cart_items.each do |item|
        @cart_value += item.price
      end
    else
      redirect_to root_path
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    if user_signed_in?
      @cart = current_user.cart

      @order = Order.new

      #inject cart item into order
      @cart.items.each do |item|
        @order << item
      end


      @order_value = 0
      @order.items.each do |item|
        @order_value += item.price
      end

      #re-initialize cart
      @cart.reset

      #redirected to order create

      end
    else
      redirect_to root_path
    end
    
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	if user_signed_in?
      @cart = current_user.cart
      @cart_items = @cart.items

      @cart_value = 0
      @cart_items.each do |item|
        @cart_value += item.price
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
    def index 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetThpS9</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- fonts -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render "shared/notice" %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_alert.html.erb
<div class="alert alert-danger" role="alert"> <%= alert%> </div>

app/views/shared/_footer.html.erb
<!------------------------ Footer -------------------------->
    <div id="footer">
      <div class="footer-widget">
        <div class="footer-text">
          <div class="container">
            <p>Designed and Developed by <a href="">Montprellier Team </a> from The Hacking Project</p>
         </div>
        </div>
      </div>
    </div>
<!------------- End-Footer ----------------->

app/views/shared/_navbar.html.erb
<!--------------------------------- NAVBAR -------------------------------->
    <nav> 
      <div class="top"> <!--------------- top ---------------->
        <div class="user-connected">
          <% if user_signed_in? %>
            <%= current_user.email %>
          <% end %>
        </div>
        <div class="top-control">
          <% if user_signed_in? %>
            <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %> <br>
          <% else %>
            <%= link_to 'Se créer un compte', new_user_registration_path %><span>•••</span><%= link_to 'Se connecter', new_user_session_path %>
          <% end %>
        </div>
        <div class="clearfix">
          <!-- purple nav-bar -->
        </div>
      </div><!------------------ top -------------------->

      <div id="believe-nav"> <!------ white nav-bar ------->
        <div class="container">
          <div class="min-marg">
            <nav class="navbar navbar-default">
              <div class="navbar-header">
                <a class="navbar-brand">
                  <%= link_to root_path, turbolinks: false do %>
                   <%= image_tag 'logofish1.png', alt: ""%>
                   <% end %>
                </a>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="active">
                      <%= link_to 'Le pire enemie du poisson...', "http://pussycat-shop-bg.herokuapp.com/", class: "acceuil", :target => "_blank" %>
                  </li>
                  <li>
                    <% if user_signed_in? %>
                      <%= link_to 'Mon profil', profile_path, class: "profile" %>
                    <% end %>
                  </li>
                  <li>
                    <% if user_signed_in? %>
                      <% if current_user.admin? %>
                        <%= link_to 'Dashboard admin', admin_path, class: "profile" %>
                      <% end %>
                    <% end %>
                  </li>
                </ul>
                
                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <!-- Display cart image and items number in cart (only if user signed_in) -->
                    <% if user_signed_in? %>
                      <a href="<%= carts_show_path %>" >
                        <%= image_tag('bag.png', alt: "bag") %>
                      <span id="cart_items_number"> <%= current_user.cart.items.count %> </span></a>
                    <% end %>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div> <!-------------- end white nav-bar ------------->
    </nav> 
<!--------------------------------- END NAVBAR ------------------------------------->

app/views/shared/_notice.html.erb
<% flash.each do |key, value| %>
 <div class="alert alert-<%= key %>">
   <a href="#" data-dismiss="alert" class="close">×</a>
   <ul>
     <li>
       <%= value %>
     </li>
   </ul>
 </div>
<% end %>