config/routes.rb
Rails.application.routes.draw do
  get '/admin', to:'home#admin'
  root to: 'home#index'
  get 'orders/show/:order_id', to:'order#show', as: 'orders_show'
  get 'orders/new', to:'order#new'

  #Carts routes
  get 'carts/show', to:'carts#show'
 
  post 'carts/create', to:'carts#create'
  post 'carts/add_item/:item_id', to:'carts#add_item', as: 'carts_add_item'
  post 'carts/remove_item', to:'carts#remove_item'
  post 'carts/reset', to:'carts#reset'
  #User_Profile routes
  get '/profile', to: 'home#profile'
  #User_Orders routes
  get '/order/:order_id', to: 'home#user_order', as: 'order'
  #Stripe routes
  get'/store', to:'store#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :charges
  resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true
    validates :image, presence: true
    has_and_belongs_to_many :carts
    # un produit appartient et possede plusieurs commandes
    has_and_belongs_to_many :orders

end

app/models/order.rb
class Order < ApplicationRecord
    #cette commande appartient à cet utilisateur précisément, qu'un seul client par commande.
    #et une commande ne peux servir qu'une seule fois.
    belongs_to :user
    has_and_belongs_to_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :cart

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable      
  #un user peux passer plusieurs commandes.
  has_many :orders

  #create a cart associate to the new user
  after_create do
    Cart.create(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  #show all items of the cart
  def show
    #select the cart of the log-in user
    if user_signed_in?
      @cart = current_user.cart
      @cart_items = @cart.items

      @cart_value = 0
      @cart_items.each do |item|
        @cart_value += item.price
      end
    else
      redirect_to root_path
    end
  end

  def create
  end

  #add item to the cart
  def add_item  
    #params[item_id]
    if user_signed_in?
      cart = current_user.cart
      item = Item.find(params["item_id"])
      @item_id = item.id
      if cart.items << item
        @items_number = cart.items.count
        puts "#"*20
        puts @item_id 
        respond_to do |format|
          format.html { redirect_to root_path }
          format.js
          #Display an SUCCESS mesage      
          #flash[:notice] = "Item succesfuly added"
        end
      else
        #Display an ERR message
      end
    else
      redirect_to root_path
    end
  end

  #remove item from the cart
  def remove_item
    item = Item.find(params["format"])
    #select the cart of the log-in user
    if user_signed_in?
      cart = current_user.cart
      #check if the item is in the cart
      if item.carts.find(cart.id)
        item.carts.delete(cart)
      end
      redirect_to carts_show_path
    else
      redirect_to root_path
    end
  end

  #re-initialize cart
  def reset
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create

		if user_signed_in?
      @cart = current_user.cart
			@cart_items = @cart.items

			#Creation of the order
			@order = Order.create(user_id: current_user.id)
			@cart_items.each do |item| 
				@order.items << item
			end
			
			#order value
			@order_value = 0
			@order.items.each do |item|
				@order_value += item.price
      end

			#re-initialize cart
			@cart_items.each do |item|
				if item.carts.find(@cart.id)
					item.carts.delete(@cart)
				end
			end

			#Send Email to User
			ContactMailer.order(@order, current_user.email).deliver_now
			#Send Email to Admin (ddaviger9@yahoo.fr)
			ContactMailer.order(@order, 'ddaviger9@yahoo.fr').deliver_now

	    else
	      redirect_to root_path
	    end

  		# Amount in cents
	  	@amount = @order_value * 100

	 	 customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  	)

	  	charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount.to_i,
	    :description => 'Downloading files',
	    :currency    => 'eur'
	  	)

		rescue Stripe::CardError => e
	 	flash[:error] = e.message
	  	redirect_to :root

	  	if Order.find_by(current_user.id)
	  		Cart.destroy
	  	end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @items = Item.all
    @admin = User.find_by(admin: true)
    
    @cart_items_id = []
    if user_signed_in?
      current_user.cart.items.each do |item|
        @cart_items_id << item.id
      end
    end

  end

  def show
  	@item_id = Item.find(params[:id])
  end


  def admin
  	@all_users = User.all
  end

  def profile
  	@orders = current_user.orders
  end

  def user_order
    @order = Order.find(params[:order_id])
  end


end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def show
    if user_signed_in?
      @order = Order.find(params['order_id'])
      #order value
      @order_value = 0
			@order.items.each do |item|
				@order_value += item.price
      end
    else
      redirect_to root_path
    end
  end

  def new
    if user_signed_in?
      @cart = current_user.cart
      @cart_items = @cart.items

      @cart_value = 0
      @cart_items.each do |item|
        @cart_value += item.price
      end
    else
      redirect_to root_path
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    if user_signed_in?
      @cart = current_user.cart

      @order = Order.new

      #inject cart item into order
      @cart.items.each do |item|
        @order << item
      end


      @order_value = 0
      @order.items.each do |item|
        @order_value += item.price
      end

      #re-initialize cart
      @cart.reset

      #redirected to order create

      end
    else
      redirect_to root_path
    end
    
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	if user_signed_in?
      @cart = current_user.cart
      @cart_items = @cart.items

      @cart_value = 0
      @cart_items.each do |item|
        @cart_value += item.price
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
    def index 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/carts/add_item.js.erb
$('#<%= @item_id %>.img-responsive').parent().parent().parent().parent().parent().fadeOut();
$('#cart_items_number').text('<%= @items_number %>');

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/show.html.erb
<div class="bgcolCart">

  <section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">E-COMMERCE CART</h1>
        <h2>Cart of <%= current_user.email %> </h2>
     </div>
  </section>

  <div class="container mb-4">
      <div class="row">
          <div class="col-12">
              <div class="table-responsive" id="tableCart">
                  <table class="table table-striped" >
                      <thead>
                          <tr>
                              <th scope="col"> </th>
                              <th scope="col">Product</th>
                              <th scope="col">Available</th>
                              <th scope="col" class="text-center">Quantity</th>
                              <th scope="col" class="text-right">Price</th>
                              <th> </th>
                          </tr>
                      </thead>
                      <tbody>
                          <% @cart_items.each do |item| %>
                          <tr>
                              <td><%= image_tag(item.image, class: "img-responsive", id: item.id, alt: "") %></td>
                              <td><%= item.title %></td>
                              <td>In stock</td>
                              <td><input class="form-control" type="text" value="1" /></td>
                              <td class="text-right"><%= item.price %> €</td>
                              <td class="text-right"><%= link_to 'Supprimer', carts_remove_item_path(item.id), class:"btn btn-link", id:"btnSupp", method: :post %></td>
                          </tr>
                          <% end %>
                          <tr>
                              <td></td>
                              <td></td>
                              <td></td>
                              <td></td>
                              <td><strong>Total</strong></td>
                              <td class="text-right"><strong><%= @cart_value %> €</strong></td>
                          </tr>
                      </tbody>
                  </table>
              </div>
          </div>
          <br><br>
          <div class="col mb-2">
              <div class="row">
                  <div class="col-sm-12  col-md-6">
                      <%= link_to 'Continuer shopping', :root, class:"btn btn-link", id:"btnBack" %>
                  </div>
                  <div class="col-sm-12 col-md-6 text-right">
                      <%= link_to 'Passer commande', orders_new_path, class:"btn btn-link", id:"btnPayment" %>
                  </div>
                  <br><br><br>
              </div>
          </div>
      </div>
  </div>

</div>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/charges/create.html.erb
<div class="bgcol">

  <section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading"> Thanks for your purchase !</h1>
        <h2> User informations : <%= current_user.email %> </h2>
     </div>
  </section>

  <br><br>

  <div id="displayThks">
	  <div class="container" id="displayConfirm">
	    <div id="imgThks"><p><%= image_tag "thanks.gif" %></p></div>
	    <div><h3 class="text-center" id="textJustify"><strong>Your files have been sent !</strong></h3></div>
	    <br><br>
    <div><%= link_to 'Acheter plus d images !', root_path, class:"btn btn-link", id:"btnBack"%></div>
    <br>
    <div><%= link_to 'Details de votre commande !', orders_show_path(@order.id) , class:"btn btn-link", id:"btnBack"%></div>
	  </div>
  </div>

</div>

app/views/home/index.html.erb
<!--------------------------------- Slider ----------------------------------------->
    <div id="main-slider"> 

              <div id="home-slider" class="owl-carousel owl-theme">
                  <div class="item">
                    <%= image_tag('slider-1.jpg', class: "img-responsive", alt: "slide-1") %>
                      <div class="slider-desc">
                          <div class="container">
                              <div class="row">
                                  <div class="col-md-6">
                                      <div class="slide-offers-left promo__fish">
                                          <div class="slide-offers-title"><span>POISSON</span><br/>FISHION</div>
                                          <p>New & Fresh collection<br/>From CAAAARAIBE !!</p>
                                          <a class="btn btn-blue">Adopt now</a>
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                       <div class="slide-offers-right promo__fish">
                                          <div class="slide-offers-title"><span>BALEINE</span><br/>FISHION</div>
                                          <p>Classical & Vintage collection<br/>Vivre avec une Baleine</p>
                                          <a class="btn btn-magenta">Adopt now</a>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="item">
                    <%= image_tag('slider-2.jpg', class: "img-responsive", alt: "slide-2") %>
                      <div class="slider-desc">
                          <div class="container">
                              <div class="row">
                                  <div class="col-md-6">
                                      <div class="slide-offers-left promo__fish">
                                          <div class="slide-offers-title"><span>50% Reduction</span><br/>sur les poissons pannés</div>
                                            <p>Fish & Chips collection<br/>On vous attend dans nos magazins</p>
                                            <a class="btn btn-blue">Adopt now</a>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
    </div>    
<!--------------------------------- End-Slider ----------------------------------------->

    <div class="newest">
      <div class="container">
        <div class="newest-content">
          <div class="newest-tab">
      <!--PARTIE MENU DE NAVIGATION A AFFICHER QUE POUR LES LOGINED ???-->
            <ul id="myTab" class="nav nav-tabs newest" role="tablist">
              <li role="presentation" class="active">
                <a href="#1" id="cat-1" role="tab" data-toggle="tab" aria-controls="1" aria-expanded="true">Nos poissons</a>
              </li>
            </ul>
      <!--/////////////////////////////////////////////////////////-->
          <div id="myTabContent" class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="1" aria-labelledby="cat-1">
              <div class="row clearfix">
                <% @items.each do |element| %>
                  <% if (@cart_items_id.include?(element.id)) %>
                  <% else %>
                    <div class="col-md-3 prdct-grid">
                      <div class="product-fade">
                        <div class="product-fade-wrap">
                          <div id="product-image">
                            <div class="item">
                              <%= image_tag(element.image, class: "img-responsive", id: element.id, alt: "") %>
                            </div>
                          </div>
                          <div class="product-fade-ct">
                            <div class="product-fade-control">
                              <div class="to-left">
                                <a href=""></a>
                                <a href=""></a>
                                <a href=""></a>
                              </div>
                              <span class="bag" style=' margin-left: 40px';></span>
                                <%=link_to 'Add To cart',carts_add_item_path(element.id), class:"btn btn-to-cart", remote: true, method: :post %>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="product-name">
                        <%= link_to element.title, home_path(element.id)  %>
                      </div>
                      <div class="product-price">
                        <span>25</span> - <%= sprintf('%.2f', element.price.to_i) %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> <!-------------- end newest ------------->
    <div class="content-offers">
      <div class="container">
        <div class="ct-offers promo">
          <div class="ct-offers-title">Super Promo <br> NOEL</div>
            <p>Offrez la plus belle des expériences a vos enfants pour les fêtes.</p>
            <a class="btn btn-blue">Adopt a shark NOW!</a>
          </div>
        </div>
      </div>
    </div> <!-------------- Content offers ------->
</div> <!-- end-wrapper -->

app/views/home/item.js.erb
$(document).ready(function() {

	
	$("#fish1")
	alert('Votre produit a été ajouté à votre panier')

});
 

app/views/home/profile.html.erb
	<div class="bgcol">
		<div class="user-greeting">
			<h2>Bonjour <%= current_user.email %></h2>
		</div>
		<div class="orders-list">
			<h4>Voici l'historique de vos commandes:</h4>
			<br>
			<% @orders.each do |order| %>
			<p><strong>Commande n° : </strong><%= order.id %></p>
			<br>
			<p><strong>Commandé le : </strong><%= order.created_at %></p>
			<div class="btn btn-primary">
			<%= link_to 'Voire le contenu de la comande', order_path(order.id), class: 'order-link' %> 
			</div>
      <br>
      <% end %>
		</div>
		<br>
		<br>
		<div class="edit-profile">
			<div class="myButton">
				<%= link_to 'Editer mon Compte', edit_user_registration_path, class: 'btn-edit-profile' %> 
			</div>
			<div class="myButton">
				<%= link_to 'Page principale', root_path, class: 'btn-edit-profile' %> 
			</div>
		</div>
	</div>

app/views/home/user_order.html.erb
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading"> Voici le détail de votre commande N° <%= @order.id %></h1>
         </div>
    </section>

    <div class="container mb-4">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">N° de Produit</th>
                                <th scope="col">Image</th>
                                <th scope="col">Nom du produit</th>
                                <th scope="col">Description</th>
                                <th scope="col" class="text-center">Quantity</th>
                                <th scope="col" class="text-right">Prix</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @order.items.each do |item| %>
                              <tr>
                                  <td><%= item.id %></td>
                                  <td><%= image_tag(item.image, class: "img-responsive", alt: "") %></td>
                                  <td><%= item.title %></td>
                                  <td><%= item.description %></td>
                                  <td><input class="form-control" type="text" value="1" /></td>
                                  <td class="text-right"><%= item.price %></td>
                              </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col mb-2">
                <div class="row">
                    <div class="col-sm-12 col-md-6 text-right">
                      <%= link_to 'Retour au profil', profile_path, class: 'btn btn-lg btn-block btn-success text-uppercase' %> 
                    </div>
                </div>
                <br>
                <br>
            </div>
        </div>
    </div>

app/views/home/user_orders.html.erb
<div id="believe-nav"> <!-- Nav -->
        <div class="container">
          <div class="min-marg">
            <nav class="navbar navbar-default">
                   <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">
                  <%= image_tag('logo.png', alt: "") %>
                </a>
              </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="active">
                    <a href="index.html">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li>
                    <a href="blog.html">Blog</a>
                  </li>
                  <li>
                    <a href="blog-detail.html">Blog Post</a>
                  </li>
                  <li>
                    <a href="contact.html">Contact</a>
                  </li>
                  <li>
                    <a href="#">Buy Pro Version</a>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class="menu-search-form">
                    <a href="#" id="open-srch-form">
                      <%= image_tag('srch.png', alt: "srch") %>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <%= image_tag('pav.png', alt: "pav") %>
                    <span>2</span></a>
                  </li>
                  <li>
                    <a href="#">
                      <%= image_tag('bag.png', alt: "bag") %>
                    <span>2</span></a>
                  </li>
                  <li id="open-srch-form-mod">
                    <div>
                      <form class="side-search">
                        <div class="input-group">
                          <input type="text" class="form-control search-wid" placeholder="Search Here" aria-describedby="basic-addon1">
                          <a href="" class="input-group-addon btn-side-serach" id="basic-addon1"></a>
                        </div>
                      </form>
                    </div>
                  </li>
                </ul>
            </nav>
          </div>
        </div>

        <div class="srch-form">
          <form class="side-search">
            <div class="input-group">
              <input type="text" class="form-control search-wid" placeholder="Search Here" aria-describedby="basic-addon2">
              <a href="" class="input-group-addon btn-side-serach" id="basic-addon2"></a>
            </div>
          </form>
        </div>
      </div> <!-- Nav -->

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Voici le détail de votre commande</h1>
         </div>
    </section>

    <div class="container mb-4">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">N° de Produit</th>
                                <th scope="col">Image</th>
                                <th scope="col">Nom du produit</th>
                                <th scope="col">Description</th>
                                <th scope="col" class="text-center">Quantity</th>
                                <th scope="col" class="text-right">Prix</th>
                            </tr>
                        </thead>
                        <tbody>
                          <% @orders.each do |order| %>
                            <% order.items.each do |item| %>
                            <tr>
                                <td><%= item.id %></td>
                                <td><%= image_tag(item.image, class: "img-responsive", alt: "") %></td>
                                <td><%= item.title %></td>
                                <td><%= item.description %></td>
                                <td><input class="form-control" type="text" value="1" /></td>
                                <td class="text-right"><%= item.price %></td>
                            </tr>
                            <% end %>
                          <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col mb-2">
                <div class="row">
                    <div class="col-sm-12 col-md-6 text-right">
                      <%= link_to 'Retour au profil', profile_path, class: 'btn btn-lg btn-block btn-success text-uppercase' %> 
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/order/new.html.erb
<div class="bgcol">
	<div class="container">
	    <div class="row">
	        <div class="col-12">
	            <div class="card">
	                <div class="card-body p-0">
	                    <div class="row p-5">
                        <h2> Veuillez valider votre commande </h2>
	                    </div>
	                    <hr class="my-5">

	                    <div class="row pb-5 p-5">
	                        <div class="col-md-6">
	                            <p class="font-weight-bold mb-4">Client Information</p>
	                            <p class="mb-1"><%= current_user.email %></p>
	                        </div>

	                        <div class="col-md-6 text-right">
	                            <p class="font-weight-bold mb-4">Payment Details</p>
	                            <p class="mb-1"><span class="text-muted">COMMAND ID </span> <%= @cart.id %></p>
	                            <p class="mb-1"><span class="text-muted">USER ID: </span> <%= current_user.id %></p>
	                            <p class="mb-1"><span class="text-muted">Payment Type: </span> CB</p>
	                            <p class="mb-1"><span class="text-muted">Locality: </span> France</p>
	                        </div>
	                    </div>

	                    <div class="row p-5">
	                        <div class="col-md-12">
	                            <table class="table">
	                                <thead>
	                                    <tr>
	                                        <th class="border-0 text-uppercase small font-weight-bold">ID</th>
	                                        <th class="border-0 text-uppercase small font-weight-bold">Item</th>
	                                        <th class="border-0 text-uppercase small font-weight-bold">Description</th>
	                                        <th class="border-0 text-uppercase small font-weight-bold">Quantity</th>
	                                        <th class="border-0 text-uppercase small font-weight-bold">Unit Cost</th>
	                                        <th class="border-0 text-uppercase small font-weight-bold">Total</th>
	                                    </tr>
	                                </thead>
	                                <tbody>
	                                	<% @cart_items.each do |item| %>
		                                    <tr>
		                                        <td><%= item.id %></td>
		                                        <td><%= item.title %></td>
		                                        <td><%= item.description %></td>
		                                        <td>1</td>
		                                        <td><%= item.price %></td>
		                                        <td><%= item.price %></td>
		                                    </tr>
	                                    <% end %>
	                                </tbody>
	                            </table>
	                        </div>
	                    </div>

	                    <div class="d-flex flex-row-reverse bg-dark text-white p-4">
	                        <div class="py-3 px-5 text-right">
	                            <div class="mb-2">Grand Total</div>
	                            <div class="h2 font-weight-light"><%= @cart_value %> €</div>
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>
	    </div>
	    <%= link_to 'Confirmer commande', store_path, class:"btn btn-link", id:"btnPayment" %>
	</div>
</div>

app/views/store/index.html.erb
<div class="bgcol">

  <section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">PAYMENT</h1>
        <h2>User informations : <%= current_user.email %> </h2>
     </div>
  </section>

  <br><br>

  <div class="container" id="displayBank">
    <div class="col-md-4">
        <div class="panel panel-info" id="displayPay">
            <div class="panel-heading">
                <h4 class="text-center">Details of the payment</h4>
            </div>
            <div class="panel-body text-center">
                <p class="lead">
                    <h1><strong><%= @cart_value %> €</strong></h1>
                </p>
            </div>
            <ul class="list-group list-group-flush text-center">
                <li class="list-group-item"><i class="icon-ok text-danger"></i>Total products : <%= @cart_items.count %></li>
                <li class="list-group-item"><i class="icon-ok text-danger"></i>Files sent by email</li>
                <li class="list-group-item"><i class="icon-ok text-danger"></i>7/7 support</li>
            </ul>
            <div class="panel-footer" id="btnPay">
                <%= form_tag charges_path, class: "payment-form" do %>
                  <article>
                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>
                  </article>
                  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                          data-description="Payer mon panier"
                          data-amount="<%= @cart_value * 100 %>"
                          data-label="Paiment"
                          data-locale="auto"
                          data-currency="eur"
                          data-email ="<%=current_user.email%>"> Payer mon panier
                  </script>
                <% end %>
            </div>
        </div>
    </div>
  </div>
</div>